name: Setup Environment
description: Setup Node.js and cache dependencies consistently
# Note: All workflows using this action should use runs-on: ubuntu-24.04
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v5
      with:
        node-version: '20.19.5'
    - uses: './.github/actions/node-cache'