name: API client integration tests
description: Run API client integration tests against stubbed services
runs:
  using: "composite"
  steps:
    - uses: nrwl/nx-set-shas@v4
    - uses: './.github/actions/node-cache'
    - name: Install deps
      shell: bash
      run: npm i
    - name: integration test
      shell: bash
      run: npm run test:integration
