name: Node modules cache
description: Retrieve and cache project node_modules
runs:
  using: "composite"
  steps:
    # cache node modules for all jobs to use
    - uses: actions/cache@v3
      id: node_modules-cache
      with:
        path: | 
          **/node_modules
        key: install-cache-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}