/* tslint:disable */
/* eslint-disable */
import { APIFactory } from '@redhat-cloud-services/javascript-clients-shared/dist/utils';
import { ApiConfig } from '@redhat-cloud-services/javascript-clients-shared/dist/common'
import {
    assignRule,
    assignRules,
    assignSystem,
    assignSystems,
    createPolicy,
    createTailoring,
    deletePolicy,
    deleteReport,
    policies,
    policy,
    policySystems,
    policySystemsOS,
    profile,
    profileRule,
    profileRules,
    profileTree,
    profiles,
    report,
    reportRuleResults,
    reportStats,
    reportSystem,
    reportSystems,
    reportSystemsOS,
    reportTestResult,
    reportTestResults,
    reportTestResultsOS,
    reportTestResultsSG,
    reports,
    reportsOS,
    rule,
    ruleGroup,
    ruleGroups,
    rules,
    securityGuide,
    securityGuideRuleTree,
    securityGuides,
    securityGuidesOS,
    status,
    supportedProfiles,
    system,
    systemReports,
    systems,
    systemsOS,
    systemsPolicies,
    tailoring,
    tailoringFileJSON,
    tailoringFileTOML,
    tailoringRuleTree,
    tailoringRules,
    tailorings,
    unassignRule,
    unassignSystem,
    updatePolicy,
    updateTailoring,
    valueDefinition,
    valueDefinitions,

  } from './index';

const endpointList = {
      assignRule,
    assignRules,
    assignSystem,
    assignSystems,
    createPolicy,
    createTailoring,
    deletePolicy,
    deleteReport,
    policies,
    policy,
    policySystems,
    policySystemsOS,
    profile,
    profileRule,
    profileRules,
    profileTree,
    profiles,
    report,
    reportRuleResults,
    reportStats,
    reportSystem,
    reportSystems,
    reportSystemsOS,
    reportTestResult,
    reportTestResults,
    reportTestResultsOS,
    reportTestResultsSG,
    reports,
    reportsOS,
    rule,
    ruleGroup,
    ruleGroups,
    rules,
    securityGuide,
    securityGuideRuleTree,
    securityGuides,
    securityGuidesOS,
    status,
    supportedProfiles,
    system,
    systemReports,
    systems,
    systemsOS,
    systemsPolicies,
    tailoring,
    tailoringFileJSON,
    tailoringFileTOML,
    tailoringRuleTree,
    tailoringRules,
    tailorings,
    unassignRule,
    unassignSystem,
    updatePolicy,
    updateTailoring,
    valueDefinition,
    valueDefinitions,


};

export const ComplianceClient = (BASE_PATH: string, instance?: ApiConfig) => {
  return APIFactory(BASE_PATH, endpointList, instance);
}

export default ComplianceClient;
