/* tslint:disable */
/* eslint-disable */
import type { AxiosStatic } from 'axios'
import { APIFactory } from '@redhat-cloud-services/javascript-clients-shared/dist/utils';
import { ApiConfig } from '@redhat-cloud-services/javascript-clients-shared/dist/common'
import {
    assignRule,AssignRuleReturnType,
    assignRules,AssignRulesReturnType,
    assignSystem,AssignSystemReturnType,
    assignSystems,AssignSystemsReturnType,
    createPolicy,CreatePolicyReturnType,
    createTailoring,CreateTailoringReturnType,
    deletePolicy,DeletePolicyReturnType,
    deleteReport,DeleteReportReturnType,
    policies,PoliciesReturnType,
    policy,PolicyReturnType,
    policySystems,PolicySystemsReturnType,
    policySystemsOS,PolicySystemsOSReturnType,
    profile,ProfileReturnType,
    profileRule,ProfileRuleReturnType,
    profileRules,ProfileRulesReturnType,
    profileTree,ProfileTreeReturnType,
    profiles,ProfilesReturnType,
    report,ReportReturnType,
    reportRuleResults,ReportRuleResultsReturnType,
    reportStats,ReportStatsReturnType,
    reportSystem,ReportSystemReturnType,
    reportSystems,ReportSystemsReturnType,
    reportSystemsOS,ReportSystemsOSReturnType,
    reportTestResult,ReportTestResultReturnType,
    reportTestResults,ReportTestResultsReturnType,
    reportTestResultsOS,ReportTestResultsOSReturnType,
    reportTestResultsSG,ReportTestResultsSGReturnType,
    reports,ReportsReturnType,
    reportsOS,ReportsOSReturnType,
    rule,RuleReturnType,
    ruleGroup,RuleGroupReturnType,
    ruleGroups,RuleGroupsReturnType,
    rules,RulesReturnType,
    securityGuide,SecurityGuideReturnType,
    securityGuideRuleTree,SecurityGuideRuleTreeReturnType,
    securityGuides,SecurityGuidesReturnType,
    securityGuidesOS,SecurityGuidesOSReturnType,
    supportedProfiles,SupportedProfilesReturnType,
    system,SystemReturnType,
    systemReports,SystemReportsReturnType,
    systems,SystemsReturnType,
    systemsOS,SystemsOSReturnType,
    systemsPolicies,SystemsPoliciesReturnType,
    tailoring,TailoringReturnType,
    tailoringFile,TailoringFileReturnType,
    tailoringRuleTree,TailoringRuleTreeReturnType,
    tailoringRules,TailoringRulesReturnType,
    tailorings,TailoringsReturnType,
    unassignRule,UnassignRuleReturnType,
    unassignSystem,UnassignSystemReturnType,
    updatePolicy,UpdatePolicyReturnType,
    updateTailoring,UpdateTailoringReturnType,
    valueDefinition,ValueDefinitionReturnType,
    valueDefinitions,ValueDefinitionsReturnType,

  } from './index';

const endpointList = {
      assignRule,
    assignRules,
    assignSystem,
    assignSystems,
    createPolicy,
    createTailoring,
    deletePolicy,
    deleteReport,
    policies,
    policy,
    policySystems,
    policySystemsOS,
    profile,
    profileRule,
    profileRules,
    profileTree,
    profiles,
    report,
    reportRuleResults,
    reportStats,
    reportSystem,
    reportSystems,
    reportSystemsOS,
    reportTestResult,
    reportTestResults,
    reportTestResultsOS,
    reportTestResultsSG,
    reports,
    reportsOS,
    rule,
    ruleGroup,
    ruleGroups,
    rules,
    securityGuide,
    securityGuideRuleTree,
    securityGuides,
    securityGuidesOS,
    supportedProfiles,
    system,
    systemReports,
    systems,
    systemsOS,
    systemsPolicies,
    tailoring,
    tailoringFile,
    tailoringRuleTree,
    tailoringRules,
    tailorings,
    unassignRule,
    unassignSystem,
    updatePolicy,
    updateTailoring,
    valueDefinition,
    valueDefinitions,


};

type endpointReturnTypes = {
      assignRule: AssignRuleReturnType,
    assignRules: AssignRulesReturnType,
    assignSystem: AssignSystemReturnType,
    assignSystems: AssignSystemsReturnType,
    createPolicy: CreatePolicyReturnType,
    createTailoring: CreateTailoringReturnType,
    deletePolicy: DeletePolicyReturnType,
    deleteReport: DeleteReportReturnType,
    policies: PoliciesReturnType,
    policy: PolicyReturnType,
    policySystems: PolicySystemsReturnType,
    policySystemsOS: PolicySystemsOSReturnType,
    profile: ProfileReturnType,
    profileRule: ProfileRuleReturnType,
    profileRules: ProfileRulesReturnType,
    profileTree: ProfileTreeReturnType,
    profiles: ProfilesReturnType,
    report: ReportReturnType,
    reportRuleResults: ReportRuleResultsReturnType,
    reportStats: ReportStatsReturnType,
    reportSystem: ReportSystemReturnType,
    reportSystems: ReportSystemsReturnType,
    reportSystemsOS: ReportSystemsOSReturnType,
    reportTestResult: ReportTestResultReturnType,
    reportTestResults: ReportTestResultsReturnType,
    reportTestResultsOS: ReportTestResultsOSReturnType,
    reportTestResultsSG: ReportTestResultsSGReturnType,
    reports: ReportsReturnType,
    reportsOS: ReportsOSReturnType,
    rule: RuleReturnType,
    ruleGroup: RuleGroupReturnType,
    ruleGroups: RuleGroupsReturnType,
    rules: RulesReturnType,
    securityGuide: SecurityGuideReturnType,
    securityGuideRuleTree: SecurityGuideRuleTreeReturnType,
    securityGuides: SecurityGuidesReturnType,
    securityGuidesOS: SecurityGuidesOSReturnType,
    supportedProfiles: SupportedProfilesReturnType,
    system: SystemReturnType,
    systemReports: SystemReportsReturnType,
    systems: SystemsReturnType,
    systemsOS: SystemsOSReturnType,
    systemsPolicies: SystemsPoliciesReturnType,
    tailoring: TailoringReturnType,
    tailoringFile: TailoringFileReturnType,
    tailoringRuleTree: TailoringRuleTreeReturnType,
    tailoringRules: TailoringRulesReturnType,
    tailorings: TailoringsReturnType,
    unassignRule: UnassignRuleReturnType,
    unassignSystem: UnassignSystemReturnType,
    updatePolicy: UpdatePolicyReturnType,
    updateTailoring: UpdateTailoringReturnType,
    valueDefinition: ValueDefinitionReturnType,
    valueDefinitions: ValueDefinitionsReturnType,


};

export const ComplianceClient = (BASE_PATH: string, instance?: ApiConfig) => {
  return APIFactory<typeof endpointList, endpointReturnTypes>(BASE_PATH, endpointList, instance);
}

export default ComplianceClient;
