/* tslint:disable */
/* eslint-disable */
import type { AxiosStatic } from 'axios'
import { APIFactory } from '@redhat-cloud-services/javascript-clients-shared/dist/utils';
import { ApiConfig } from '@redhat-cloud-services/javascript-clients-shared/dist/common'
import {
    appliedInventoriesForServiceOffering,AppliedInventoriesForServiceOfferingReturnType,
    getDocumentation,GetDocumentationReturnType,
    listClusterHosts,ListClusterHostsReturnType,
    listClusters,ListClustersReturnType,
    listContainerGroupContainers,ListContainerGroupContainersReturnType,
    listContainerGroupTags,ListContainerGroupTagsReturnType,
    listContainerGroups,ListContainerGroupsReturnType,
    listContainerImageTags,ListContainerImageTagsReturnType,
    listContainerImages,ListContainerImagesReturnType,
    listContainerNodeContainerGroups,ListContainerNodeContainerGroupsReturnType,
    listContainerNodeTags,ListContainerNodeTagsReturnType,
    listContainerNodes,ListContainerNodesReturnType,
    listContainerProjectContainerGroups,ListContainerProjectContainerGroupsReturnType,
    listContainerProjectContainerResourceQuota,ListContainerProjectContainerResourceQuotaReturnType,
    listContainerProjectContainerTemplates,ListContainerProjectContainerTemplatesReturnType,
    listContainerProjectTags,ListContainerProjectTagsReturnType,
    listContainerProjects,ListContainerProjectsReturnType,
    listContainerResourceQuota,ListContainerResourceQuotaReturnType,
    listContainerTemplateTags,ListContainerTemplateTagsReturnType,
    listContainerTemplates,ListContainerTemplatesReturnType,
    listContainers,ListContainersReturnType,
    listDatastores,ListDatastoresReturnType,
    listFlavors,ListFlavorsReturnType,
    listHosts,ListHostsReturnType,
    listIpaddressTags,ListIpaddressTagsReturnType,
    listIpaddresses,ListIpaddressesReturnType,
    listNetworkAdapterIpaddresses,ListNetworkAdapterIpaddressesReturnType,
    listNetworkAdapterTags,ListNetworkAdapterTagsReturnType,
    listNetworkAdapters,ListNetworkAdaptersReturnType,
    listNetworkSubnets,ListNetworkSubnetsReturnType,
    listNetworkTags,ListNetworkTagsReturnType,
    listNetworks,ListNetworksReturnType,
    listOrchestrationStackIpaddresses,ListOrchestrationStackIpaddressesReturnType,
    listOrchestrationStackNetworkAdapters,ListOrchestrationStackNetworkAdaptersReturnType,
    listOrchestrationStackNetworks,ListOrchestrationStackNetworksReturnType,
    listOrchestrationStackSecurityGroups,ListOrchestrationStackSecurityGroupsReturnType,
    listOrchestrationStackSubnets,ListOrchestrationStackSubnetsReturnType,
    listOrchestrationStackVms,ListOrchestrationStackVmsReturnType,
    listOrchestrationStackVolumes,ListOrchestrationStackVolumesReturnType,
    listOrchestrationStacks,ListOrchestrationStacksReturnType,
    listSecurityGroupTags,ListSecurityGroupTagsReturnType,
    listSecurityGroupVms,ListSecurityGroupVmsReturnType,
    listSecurityGroups,ListSecurityGroupsReturnType,
    listServiceInstanceNodes,ListServiceInstanceNodesReturnType,
    listServiceInstanceServiceInstanceNodes,ListServiceInstanceServiceInstanceNodesReturnType,
    listServiceInstances,ListServiceInstancesReturnType,
    listServiceInventories,ListServiceInventoriesReturnType,
    listServiceInventoryTags,ListServiceInventoryTagsReturnType,
    listServiceOfferingIcons,ListServiceOfferingIconsReturnType,
    listServiceOfferingNodes,ListServiceOfferingNodesReturnType,
    listServiceOfferingServiceInstances,ListServiceOfferingServiceInstancesReturnType,
    listServiceOfferingServiceOfferingNodes,ListServiceOfferingServiceOfferingNodesReturnType,
    listServiceOfferingServicePlans,ListServiceOfferingServicePlansReturnType,
    listServiceOfferingTags,ListServiceOfferingTagsReturnType,
    listServiceOfferings,ListServiceOfferingsReturnType,
    listServicePlanServiceInstances,ListServicePlanServiceInstancesReturnType,
    listServicePlans,ListServicePlansReturnType,
    listSourceAvailabilities,ListSourceAvailabilitiesReturnType,
    listSourceClusters,ListSourceClustersReturnType,
    listSourceContainerGroups,ListSourceContainerGroupsReturnType,
    listSourceContainerImages,ListSourceContainerImagesReturnType,
    listSourceContainerNodes,ListSourceContainerNodesReturnType,
    listSourceContainerProjects,ListSourceContainerProjectsReturnType,
    listSourceContainerTemplates,ListSourceContainerTemplatesReturnType,
    listSourceContainers,ListSourceContainersReturnType,
    listSourceDatastores,ListSourceDatastoresReturnType,
    listSourceHosts,ListSourceHostsReturnType,
    listSourceIpaddresses,ListSourceIpaddressesReturnType,
    listSourceNetworkAdapters,ListSourceNetworkAdaptersReturnType,
    listSourceNetworks,ListSourceNetworksReturnType,
    listSourceOrchestrationStacks,ListSourceOrchestrationStacksReturnType,
    listSourceRegionIpaddresses,ListSourceRegionIpaddressesReturnType,
    listSourceRegionNetworkAdapters,ListSourceRegionNetworkAdaptersReturnType,
    listSourceRegionNetworks,ListSourceRegionNetworksReturnType,
    listSourceRegionOrchestrationStacks,ListSourceRegionOrchestrationStacksReturnType,
    listSourceRegionSecurityGroups,ListSourceRegionSecurityGroupsReturnType,
    listSourceRegionServiceInstances,ListSourceRegionServiceInstancesReturnType,
    listSourceRegionServiceOfferings,ListSourceRegionServiceOfferingsReturnType,
    listSourceRegionServicePlans,ListSourceRegionServicePlansReturnType,
    listSourceRegionSubnets,ListSourceRegionSubnetsReturnType,
    listSourceRegionVms,ListSourceRegionVmsReturnType,
    listSourceRegionVolumes,ListSourceRegionVolumesReturnType,
    listSourceRegions,ListSourceRegionsReturnType,
    listSourceSecurityGroups,ListSourceSecurityGroupsReturnType,
    listSourceServiceInstanceNodes,ListSourceServiceInstanceNodesReturnType,
    listSourceServiceInstances,ListSourceServiceInstancesReturnType,
    listSourceServiceInventories,ListSourceServiceInventoriesReturnType,
    listSourceServiceOfferingNodes,ListSourceServiceOfferingNodesReturnType,
    listSourceServiceOfferings,ListSourceServiceOfferingsReturnType,
    listSourceServicePlans,ListSourceServicePlansReturnType,
    listSourceSourceRegions,ListSourceSourceRegionsReturnType,
    listSourceSubnets,ListSourceSubnetsReturnType,
    listSourceSubscriptions,ListSourceSubscriptionsReturnType,
    listSourceVms,ListSourceVmsReturnType,
    listSourceVolumeTypes,ListSourceVolumeTypesReturnType,
    listSourceVolumes,ListSourceVolumesReturnType,
    listSources,ListSourcesReturnType,
    listSubnetIpaddresses,ListSubnetIpaddressesReturnType,
    listSubnetNetworkAdapters,ListSubnetNetworkAdaptersReturnType,
    listSubnetTags,ListSubnetTagsReturnType,
    listSubnets,ListSubnetsReturnType,
    listSubscriptionIpaddresses,ListSubscriptionIpaddressesReturnType,
    listSubscriptionNetworkAdapters,ListSubscriptionNetworkAdaptersReturnType,
    listSubscriptionNetworks,ListSubscriptionNetworksReturnType,
    listSubscriptionOrchestrationStacks,ListSubscriptionOrchestrationStacksReturnType,
    listSubscriptionSecurityGroups,ListSubscriptionSecurityGroupsReturnType,
    listSubscriptionServiceInstances,ListSubscriptionServiceInstancesReturnType,
    listSubscriptionServiceOfferings,ListSubscriptionServiceOfferingsReturnType,
    listSubscriptionServicePlans,ListSubscriptionServicePlansReturnType,
    listSubscriptionSubnets,ListSubscriptionSubnetsReturnType,
    listSubscriptionVms,ListSubscriptionVmsReturnType,
    listSubscriptionVolumes,ListSubscriptionVolumesReturnType,
    listSubscriptions,ListSubscriptionsReturnType,
    listTagContainerGroups,ListTagContainerGroupsReturnType,
    listTagContainerImages,ListTagContainerImagesReturnType,
    listTagContainerNodes,ListTagContainerNodesReturnType,
    listTagContainerProjects,ListTagContainerProjectsReturnType,
    listTagContainerTemplates,ListTagContainerTemplatesReturnType,
    listTagIpaddresses,ListTagIpaddressesReturnType,
    listTagNetworkAdapters,ListTagNetworkAdaptersReturnType,
    listTagNetworks,ListTagNetworksReturnType,
    listTagSecurityGroups,ListTagSecurityGroupsReturnType,
    listTagServiceInventories,ListTagServiceInventoriesReturnType,
    listTagServiceOfferings,ListTagServiceOfferingsReturnType,
    listTagSubnets,ListTagSubnetsReturnType,
    listTagVms,ListTagVmsReturnType,
    listTags,ListTagsReturnType,
    listTasks,ListTasksReturnType,
    listVmNetworkAdapters,ListVmNetworkAdaptersReturnType,
    listVmSecurityGroups,ListVmSecurityGroupsReturnType,
    listVmTags,ListVmTagsReturnType,
    listVmVolumeAttachments,ListVmVolumeAttachmentsReturnType,
    listVmVolumes,ListVmVolumesReturnType,
    listVms,ListVmsReturnType,
    listVolumeAttachments,ListVolumeAttachmentsReturnType,
    listVolumeTypeVolumes,ListVolumeTypeVolumesReturnType,
    listVolumeTypes,ListVolumeTypesReturnType,
    listVolumeVms,ListVolumeVmsReturnType,
    listVolumes,ListVolumesReturnType,
    orderServiceOffering,OrderServiceOfferingReturnType,
    orderServicePlan,OrderServicePlanReturnType,
    postGraphQL,PostGraphQLReturnType,
    showCluster,ShowClusterReturnType,
    showContainer,ShowContainerReturnType,
    showContainerGroup,ShowContainerGroupReturnType,
    showContainerImage,ShowContainerImageReturnType,
    showContainerNode,ShowContainerNodeReturnType,
    showContainerProject,ShowContainerProjectReturnType,
    showContainerResourceQuota,ShowContainerResourceQuotaReturnType,
    showContainerTemplate,ShowContainerTemplateReturnType,
    showDatastore,ShowDatastoreReturnType,
    showFlavor,ShowFlavorReturnType,
    showHost,ShowHostReturnType,
    showIpaddress,ShowIpaddressReturnType,
    showNetwork,ShowNetworkReturnType,
    showNetworkAdapter,ShowNetworkAdapterReturnType,
    showOrchestrationStack,ShowOrchestrationStackReturnType,
    showSecurityGroup,ShowSecurityGroupReturnType,
    showServiceInstance,ShowServiceInstanceReturnType,
    showServiceInstanceNode,ShowServiceInstanceNodeReturnType,
    showServiceInventory,ShowServiceInventoryReturnType,
    showServiceOffering,ShowServiceOfferingReturnType,
    showServiceOfferingIcon,ShowServiceOfferingIconReturnType,
    showServiceOfferingIconIconData,ShowServiceOfferingIconIconDataReturnType,
    showServiceOfferingNode,ShowServiceOfferingNodeReturnType,
    showServicePlan,ShowServicePlanReturnType,
    showSource,ShowSourceReturnType,
    showSourceRegion,ShowSourceRegionReturnType,
    showSubnet,ShowSubnetReturnType,
    showSubscription,ShowSubscriptionReturnType,
    showTag,ShowTagReturnType,
    showTask,ShowTaskReturnType,
    showVm,ShowVmReturnType,
    showVolume,ShowVolumeReturnType,
    showVolumeAttachment,ShowVolumeAttachmentReturnType,
    showVolumeType,ShowVolumeTypeReturnType,
    updateTask,UpdateTaskReturnType,

  } from './index';

const endpointList = {
      appliedInventoriesForServiceOffering,
    getDocumentation,
    listClusterHosts,
    listClusters,
    listContainerGroupContainers,
    listContainerGroupTags,
    listContainerGroups,
    listContainerImageTags,
    listContainerImages,
    listContainerNodeContainerGroups,
    listContainerNodeTags,
    listContainerNodes,
    listContainerProjectContainerGroups,
    listContainerProjectContainerResourceQuota,
    listContainerProjectContainerTemplates,
    listContainerProjectTags,
    listContainerProjects,
    listContainerResourceQuota,
    listContainerTemplateTags,
    listContainerTemplates,
    listContainers,
    listDatastores,
    listFlavors,
    listHosts,
    listIpaddressTags,
    listIpaddresses,
    listNetworkAdapterIpaddresses,
    listNetworkAdapterTags,
    listNetworkAdapters,
    listNetworkSubnets,
    listNetworkTags,
    listNetworks,
    listOrchestrationStackIpaddresses,
    listOrchestrationStackNetworkAdapters,
    listOrchestrationStackNetworks,
    listOrchestrationStackSecurityGroups,
    listOrchestrationStackSubnets,
    listOrchestrationStackVms,
    listOrchestrationStackVolumes,
    listOrchestrationStacks,
    listSecurityGroupTags,
    listSecurityGroupVms,
    listSecurityGroups,
    listServiceInstanceNodes,
    listServiceInstanceServiceInstanceNodes,
    listServiceInstances,
    listServiceInventories,
    listServiceInventoryTags,
    listServiceOfferingIcons,
    listServiceOfferingNodes,
    listServiceOfferingServiceInstances,
    listServiceOfferingServiceOfferingNodes,
    listServiceOfferingServicePlans,
    listServiceOfferingTags,
    listServiceOfferings,
    listServicePlanServiceInstances,
    listServicePlans,
    listSourceAvailabilities,
    listSourceClusters,
    listSourceContainerGroups,
    listSourceContainerImages,
    listSourceContainerNodes,
    listSourceContainerProjects,
    listSourceContainerTemplates,
    listSourceContainers,
    listSourceDatastores,
    listSourceHosts,
    listSourceIpaddresses,
    listSourceNetworkAdapters,
    listSourceNetworks,
    listSourceOrchestrationStacks,
    listSourceRegionIpaddresses,
    listSourceRegionNetworkAdapters,
    listSourceRegionNetworks,
    listSourceRegionOrchestrationStacks,
    listSourceRegionSecurityGroups,
    listSourceRegionServiceInstances,
    listSourceRegionServiceOfferings,
    listSourceRegionServicePlans,
    listSourceRegionSubnets,
    listSourceRegionVms,
    listSourceRegionVolumes,
    listSourceRegions,
    listSourceSecurityGroups,
    listSourceServiceInstanceNodes,
    listSourceServiceInstances,
    listSourceServiceInventories,
    listSourceServiceOfferingNodes,
    listSourceServiceOfferings,
    listSourceServicePlans,
    listSourceSourceRegions,
    listSourceSubnets,
    listSourceSubscriptions,
    listSourceVms,
    listSourceVolumeTypes,
    listSourceVolumes,
    listSources,
    listSubnetIpaddresses,
    listSubnetNetworkAdapters,
    listSubnetTags,
    listSubnets,
    listSubscriptionIpaddresses,
    listSubscriptionNetworkAdapters,
    listSubscriptionNetworks,
    listSubscriptionOrchestrationStacks,
    listSubscriptionSecurityGroups,
    listSubscriptionServiceInstances,
    listSubscriptionServiceOfferings,
    listSubscriptionServicePlans,
    listSubscriptionSubnets,
    listSubscriptionVms,
    listSubscriptionVolumes,
    listSubscriptions,
    listTagContainerGroups,
    listTagContainerImages,
    listTagContainerNodes,
    listTagContainerProjects,
    listTagContainerTemplates,
    listTagIpaddresses,
    listTagNetworkAdapters,
    listTagNetworks,
    listTagSecurityGroups,
    listTagServiceInventories,
    listTagServiceOfferings,
    listTagSubnets,
    listTagVms,
    listTags,
    listTasks,
    listVmNetworkAdapters,
    listVmSecurityGroups,
    listVmTags,
    listVmVolumeAttachments,
    listVmVolumes,
    listVms,
    listVolumeAttachments,
    listVolumeTypeVolumes,
    listVolumeTypes,
    listVolumeVms,
    listVolumes,
    orderServiceOffering,
    orderServicePlan,
    postGraphQL,
    showCluster,
    showContainer,
    showContainerGroup,
    showContainerImage,
    showContainerNode,
    showContainerProject,
    showContainerResourceQuota,
    showContainerTemplate,
    showDatastore,
    showFlavor,
    showHost,
    showIpaddress,
    showNetwork,
    showNetworkAdapter,
    showOrchestrationStack,
    showSecurityGroup,
    showServiceInstance,
    showServiceInstanceNode,
    showServiceInventory,
    showServiceOffering,
    showServiceOfferingIcon,
    showServiceOfferingIconIconData,
    showServiceOfferingNode,
    showServicePlan,
    showSource,
    showSourceRegion,
    showSubnet,
    showSubscription,
    showTag,
    showTask,
    showVm,
    showVolume,
    showVolumeAttachment,
    showVolumeType,
    updateTask,


};

type endpointReturnTypes = {
      appliedInventoriesForServiceOffering: AppliedInventoriesForServiceOfferingReturnType,
    getDocumentation: GetDocumentationReturnType,
    listClusterHosts: ListClusterHostsReturnType,
    listClusters: ListClustersReturnType,
    listContainerGroupContainers: ListContainerGroupContainersReturnType,
    listContainerGroupTags: ListContainerGroupTagsReturnType,
    listContainerGroups: ListContainerGroupsReturnType,
    listContainerImageTags: ListContainerImageTagsReturnType,
    listContainerImages: ListContainerImagesReturnType,
    listContainerNodeContainerGroups: ListContainerNodeContainerGroupsReturnType,
    listContainerNodeTags: ListContainerNodeTagsReturnType,
    listContainerNodes: ListContainerNodesReturnType,
    listContainerProjectContainerGroups: ListContainerProjectContainerGroupsReturnType,
    listContainerProjectContainerResourceQuota: ListContainerProjectContainerResourceQuotaReturnType,
    listContainerProjectContainerTemplates: ListContainerProjectContainerTemplatesReturnType,
    listContainerProjectTags: ListContainerProjectTagsReturnType,
    listContainerProjects: ListContainerProjectsReturnType,
    listContainerResourceQuota: ListContainerResourceQuotaReturnType,
    listContainerTemplateTags: ListContainerTemplateTagsReturnType,
    listContainerTemplates: ListContainerTemplatesReturnType,
    listContainers: ListContainersReturnType,
    listDatastores: ListDatastoresReturnType,
    listFlavors: ListFlavorsReturnType,
    listHosts: ListHostsReturnType,
    listIpaddressTags: ListIpaddressTagsReturnType,
    listIpaddresses: ListIpaddressesReturnType,
    listNetworkAdapterIpaddresses: ListNetworkAdapterIpaddressesReturnType,
    listNetworkAdapterTags: ListNetworkAdapterTagsReturnType,
    listNetworkAdapters: ListNetworkAdaptersReturnType,
    listNetworkSubnets: ListNetworkSubnetsReturnType,
    listNetworkTags: ListNetworkTagsReturnType,
    listNetworks: ListNetworksReturnType,
    listOrchestrationStackIpaddresses: ListOrchestrationStackIpaddressesReturnType,
    listOrchestrationStackNetworkAdapters: ListOrchestrationStackNetworkAdaptersReturnType,
    listOrchestrationStackNetworks: ListOrchestrationStackNetworksReturnType,
    listOrchestrationStackSecurityGroups: ListOrchestrationStackSecurityGroupsReturnType,
    listOrchestrationStackSubnets: ListOrchestrationStackSubnetsReturnType,
    listOrchestrationStackVms: ListOrchestrationStackVmsReturnType,
    listOrchestrationStackVolumes: ListOrchestrationStackVolumesReturnType,
    listOrchestrationStacks: ListOrchestrationStacksReturnType,
    listSecurityGroupTags: ListSecurityGroupTagsReturnType,
    listSecurityGroupVms: ListSecurityGroupVmsReturnType,
    listSecurityGroups: ListSecurityGroupsReturnType,
    listServiceInstanceNodes: ListServiceInstanceNodesReturnType,
    listServiceInstanceServiceInstanceNodes: ListServiceInstanceServiceInstanceNodesReturnType,
    listServiceInstances: ListServiceInstancesReturnType,
    listServiceInventories: ListServiceInventoriesReturnType,
    listServiceInventoryTags: ListServiceInventoryTagsReturnType,
    listServiceOfferingIcons: ListServiceOfferingIconsReturnType,
    listServiceOfferingNodes: ListServiceOfferingNodesReturnType,
    listServiceOfferingServiceInstances: ListServiceOfferingServiceInstancesReturnType,
    listServiceOfferingServiceOfferingNodes: ListServiceOfferingServiceOfferingNodesReturnType,
    listServiceOfferingServicePlans: ListServiceOfferingServicePlansReturnType,
    listServiceOfferingTags: ListServiceOfferingTagsReturnType,
    listServiceOfferings: ListServiceOfferingsReturnType,
    listServicePlanServiceInstances: ListServicePlanServiceInstancesReturnType,
    listServicePlans: ListServicePlansReturnType,
    listSourceAvailabilities: ListSourceAvailabilitiesReturnType,
    listSourceClusters: ListSourceClustersReturnType,
    listSourceContainerGroups: ListSourceContainerGroupsReturnType,
    listSourceContainerImages: ListSourceContainerImagesReturnType,
    listSourceContainerNodes: ListSourceContainerNodesReturnType,
    listSourceContainerProjects: ListSourceContainerProjectsReturnType,
    listSourceContainerTemplates: ListSourceContainerTemplatesReturnType,
    listSourceContainers: ListSourceContainersReturnType,
    listSourceDatastores: ListSourceDatastoresReturnType,
    listSourceHosts: ListSourceHostsReturnType,
    listSourceIpaddresses: ListSourceIpaddressesReturnType,
    listSourceNetworkAdapters: ListSourceNetworkAdaptersReturnType,
    listSourceNetworks: ListSourceNetworksReturnType,
    listSourceOrchestrationStacks: ListSourceOrchestrationStacksReturnType,
    listSourceRegionIpaddresses: ListSourceRegionIpaddressesReturnType,
    listSourceRegionNetworkAdapters: ListSourceRegionNetworkAdaptersReturnType,
    listSourceRegionNetworks: ListSourceRegionNetworksReturnType,
    listSourceRegionOrchestrationStacks: ListSourceRegionOrchestrationStacksReturnType,
    listSourceRegionSecurityGroups: ListSourceRegionSecurityGroupsReturnType,
    listSourceRegionServiceInstances: ListSourceRegionServiceInstancesReturnType,
    listSourceRegionServiceOfferings: ListSourceRegionServiceOfferingsReturnType,
    listSourceRegionServicePlans: ListSourceRegionServicePlansReturnType,
    listSourceRegionSubnets: ListSourceRegionSubnetsReturnType,
    listSourceRegionVms: ListSourceRegionVmsReturnType,
    listSourceRegionVolumes: ListSourceRegionVolumesReturnType,
    listSourceRegions: ListSourceRegionsReturnType,
    listSourceSecurityGroups: ListSourceSecurityGroupsReturnType,
    listSourceServiceInstanceNodes: ListSourceServiceInstanceNodesReturnType,
    listSourceServiceInstances: ListSourceServiceInstancesReturnType,
    listSourceServiceInventories: ListSourceServiceInventoriesReturnType,
    listSourceServiceOfferingNodes: ListSourceServiceOfferingNodesReturnType,
    listSourceServiceOfferings: ListSourceServiceOfferingsReturnType,
    listSourceServicePlans: ListSourceServicePlansReturnType,
    listSourceSourceRegions: ListSourceSourceRegionsReturnType,
    listSourceSubnets: ListSourceSubnetsReturnType,
    listSourceSubscriptions: ListSourceSubscriptionsReturnType,
    listSourceVms: ListSourceVmsReturnType,
    listSourceVolumeTypes: ListSourceVolumeTypesReturnType,
    listSourceVolumes: ListSourceVolumesReturnType,
    listSources: ListSourcesReturnType,
    listSubnetIpaddresses: ListSubnetIpaddressesReturnType,
    listSubnetNetworkAdapters: ListSubnetNetworkAdaptersReturnType,
    listSubnetTags: ListSubnetTagsReturnType,
    listSubnets: ListSubnetsReturnType,
    listSubscriptionIpaddresses: ListSubscriptionIpaddressesReturnType,
    listSubscriptionNetworkAdapters: ListSubscriptionNetworkAdaptersReturnType,
    listSubscriptionNetworks: ListSubscriptionNetworksReturnType,
    listSubscriptionOrchestrationStacks: ListSubscriptionOrchestrationStacksReturnType,
    listSubscriptionSecurityGroups: ListSubscriptionSecurityGroupsReturnType,
    listSubscriptionServiceInstances: ListSubscriptionServiceInstancesReturnType,
    listSubscriptionServiceOfferings: ListSubscriptionServiceOfferingsReturnType,
    listSubscriptionServicePlans: ListSubscriptionServicePlansReturnType,
    listSubscriptionSubnets: ListSubscriptionSubnetsReturnType,
    listSubscriptionVms: ListSubscriptionVmsReturnType,
    listSubscriptionVolumes: ListSubscriptionVolumesReturnType,
    listSubscriptions: ListSubscriptionsReturnType,
    listTagContainerGroups: ListTagContainerGroupsReturnType,
    listTagContainerImages: ListTagContainerImagesReturnType,
    listTagContainerNodes: ListTagContainerNodesReturnType,
    listTagContainerProjects: ListTagContainerProjectsReturnType,
    listTagContainerTemplates: ListTagContainerTemplatesReturnType,
    listTagIpaddresses: ListTagIpaddressesReturnType,
    listTagNetworkAdapters: ListTagNetworkAdaptersReturnType,
    listTagNetworks: ListTagNetworksReturnType,
    listTagSecurityGroups: ListTagSecurityGroupsReturnType,
    listTagServiceInventories: ListTagServiceInventoriesReturnType,
    listTagServiceOfferings: ListTagServiceOfferingsReturnType,
    listTagSubnets: ListTagSubnetsReturnType,
    listTagVms: ListTagVmsReturnType,
    listTags: ListTagsReturnType,
    listTasks: ListTasksReturnType,
    listVmNetworkAdapters: ListVmNetworkAdaptersReturnType,
    listVmSecurityGroups: ListVmSecurityGroupsReturnType,
    listVmTags: ListVmTagsReturnType,
    listVmVolumeAttachments: ListVmVolumeAttachmentsReturnType,
    listVmVolumes: ListVmVolumesReturnType,
    listVms: ListVmsReturnType,
    listVolumeAttachments: ListVolumeAttachmentsReturnType,
    listVolumeTypeVolumes: ListVolumeTypeVolumesReturnType,
    listVolumeTypes: ListVolumeTypesReturnType,
    listVolumeVms: ListVolumeVmsReturnType,
    listVolumes: ListVolumesReturnType,
    orderServiceOffering: OrderServiceOfferingReturnType,
    orderServicePlan: OrderServicePlanReturnType,
    postGraphQL: PostGraphQLReturnType,
    showCluster: ShowClusterReturnType,
    showContainer: ShowContainerReturnType,
    showContainerGroup: ShowContainerGroupReturnType,
    showContainerImage: ShowContainerImageReturnType,
    showContainerNode: ShowContainerNodeReturnType,
    showContainerProject: ShowContainerProjectReturnType,
    showContainerResourceQuota: ShowContainerResourceQuotaReturnType,
    showContainerTemplate: ShowContainerTemplateReturnType,
    showDatastore: ShowDatastoreReturnType,
    showFlavor: ShowFlavorReturnType,
    showHost: ShowHostReturnType,
    showIpaddress: ShowIpaddressReturnType,
    showNetwork: ShowNetworkReturnType,
    showNetworkAdapter: ShowNetworkAdapterReturnType,
    showOrchestrationStack: ShowOrchestrationStackReturnType,
    showSecurityGroup: ShowSecurityGroupReturnType,
    showServiceInstance: ShowServiceInstanceReturnType,
    showServiceInstanceNode: ShowServiceInstanceNodeReturnType,
    showServiceInventory: ShowServiceInventoryReturnType,
    showServiceOffering: ShowServiceOfferingReturnType,
    showServiceOfferingIcon: ShowServiceOfferingIconReturnType,
    showServiceOfferingIconIconData: ShowServiceOfferingIconIconDataReturnType,
    showServiceOfferingNode: ShowServiceOfferingNodeReturnType,
    showServicePlan: ShowServicePlanReturnType,
    showSource: ShowSourceReturnType,
    showSourceRegion: ShowSourceRegionReturnType,
    showSubnet: ShowSubnetReturnType,
    showSubscription: ShowSubscriptionReturnType,
    showTag: ShowTagReturnType,
    showTask: ShowTaskReturnType,
    showVm: ShowVmReturnType,
    showVolume: ShowVolumeReturnType,
    showVolumeAttachment: ShowVolumeAttachmentReturnType,
    showVolumeType: ShowVolumeTypeReturnType,
    updateTask: UpdateTaskReturnType,


};

export const TopologicalInventoryClient = (BASE_PATH: string, instance?: ApiConfig) => {
  return APIFactory<typeof endpointList, endpointReturnTypes>(BASE_PATH, endpointList, instance);
}

export default TopologicalInventoryClient;
