name: Unit tests
description: verify unit tests
runs:
  using: "composite"
  steps:
    - uses: nrwl/nx-set-shas@v3
    - uses: './.github/actions/node-cache'
    - name: Install deps
      shell: bash
      run: npm i
    - name: Test affected
      shell: bash
      run: npx nx affected --base=master -t test --configuration=ci
