/* tslint:disable */
/* eslint-disable */
import type { AxiosStatic } from 'axios'
import { APIFactory } from '@redhat-cloud-services/javascript-clients-shared/dist/utils';
import { ApiConfig } from '@redhat-cloud-services/javascript-clients-shared/dist/common'
import {
    baselineDelete,BaselineDeleteReturnType,
    createBaseline,CreateBaselineReturnType,
    deletesystem,DeletesystemReturnType,
    detailAdvisory,DetailAdvisoryReturnType,
    detailBaseline,DetailBaselineReturnType,
    detailSystem,DetailSystemReturnType,
    exportAdvisories,ExportAdvisoriesReturnType,
    exportAdvisorySystems,ExportAdvisorySystemsReturnType,
    exportBaselineSystems,ExportBaselineSystemsReturnType,
    exportPackageSystems,ExportPackageSystemsReturnType,
    exportPackages,ExportPackagesReturnType,
    exportSystemAdvisories,ExportSystemAdvisoriesReturnType,
    exportSystemPackages,ExportSystemPackagesReturnType,
    exportSystems,ExportSystemsReturnType,
    exportTemplateSystems,ExportTemplateSystemsReturnType,
    latestPackage,LatestPackageReturnType,
    listAdvisories,ListAdvisoriesReturnType,
    listAdvisoriesIds,ListAdvisoriesIdsReturnType,
    listAdvisorySystems,ListAdvisorySystemsReturnType,
    listAdvisorySystemsIds,ListAdvisorySystemsIdsReturnType,
    listBaseline,ListBaselineReturnType,
    listBaselineSystems,ListBaselineSystemsReturnType,
    listBaselineSystemsIds,ListBaselineSystemsIdsReturnType,
    listPackages,ListPackagesReturnType,
    listSystemAdvisories,ListSystemAdvisoriesReturnType,
    listSystemAdvisoriesIds,ListSystemAdvisoriesIdsReturnType,
    listSystemTags,ListSystemTagsReturnType,
    listSystems,ListSystemsReturnType,
    listSystemsIds,ListSystemsIdsReturnType,
    listTemplate,ListTemplateReturnType,
    listTemplateSystems,ListTemplateSystemsReturnType,
    listTemplateSystemsIds,ListTemplateSystemsIdsReturnType,
    packageSystems,PackageSystemsReturnType,
    packageSystemsIds,PackageSystemsIdsReturnType,
    packageVersions,PackageVersionsReturnType,
    removeBaselineSystems,RemoveBaselineSystemsReturnType,
    removeTemplateSystems,RemoveTemplateSystemsReturnType,
    systemPackages,SystemPackagesReturnType,
    systemVmaasJson,SystemVmaasJsonReturnType,
    systemYumUpdates,SystemYumUpdatesReturnType,
    updateBaseline,UpdateBaselineReturnType,
    updateTemplateSystems,UpdateTemplateSystemsReturnType,
    viewAdvisoriesSystems,ViewAdvisoriesSystemsReturnType,
    viewSystemsAdvisories,ViewSystemsAdvisoriesReturnType,

  } from './index';

const endpointList = {
      baselineDelete,
    createBaseline,
    deletesystem,
    detailAdvisory,
    detailBaseline,
    detailSystem,
    exportAdvisories,
    exportAdvisorySystems,
    exportBaselineSystems,
    exportPackageSystems,
    exportPackages,
    exportSystemAdvisories,
    exportSystemPackages,
    exportSystems,
    exportTemplateSystems,
    latestPackage,
    listAdvisories,
    listAdvisoriesIds,
    listAdvisorySystems,
    listAdvisorySystemsIds,
    listBaseline,
    listBaselineSystems,
    listBaselineSystemsIds,
    listPackages,
    listSystemAdvisories,
    listSystemAdvisoriesIds,
    listSystemTags,
    listSystems,
    listSystemsIds,
    listTemplate,
    listTemplateSystems,
    listTemplateSystemsIds,
    packageSystems,
    packageSystemsIds,
    packageVersions,
    removeBaselineSystems,
    removeTemplateSystems,
    systemPackages,
    systemVmaasJson,
    systemYumUpdates,
    updateBaseline,
    updateTemplateSystems,
    viewAdvisoriesSystems,
    viewSystemsAdvisories,


};

type endpointReturnTypes = {
      baselineDelete: BaselineDeleteReturnType,
    createBaseline: CreateBaselineReturnType,
    deletesystem: DeletesystemReturnType,
    detailAdvisory: DetailAdvisoryReturnType,
    detailBaseline: DetailBaselineReturnType,
    detailSystem: DetailSystemReturnType,
    exportAdvisories: ExportAdvisoriesReturnType,
    exportAdvisorySystems: ExportAdvisorySystemsReturnType,
    exportBaselineSystems: ExportBaselineSystemsReturnType,
    exportPackageSystems: ExportPackageSystemsReturnType,
    exportPackages: ExportPackagesReturnType,
    exportSystemAdvisories: ExportSystemAdvisoriesReturnType,
    exportSystemPackages: ExportSystemPackagesReturnType,
    exportSystems: ExportSystemsReturnType,
    exportTemplateSystems: ExportTemplateSystemsReturnType,
    latestPackage: LatestPackageReturnType,
    listAdvisories: ListAdvisoriesReturnType,
    listAdvisoriesIds: ListAdvisoriesIdsReturnType,
    listAdvisorySystems: ListAdvisorySystemsReturnType,
    listAdvisorySystemsIds: ListAdvisorySystemsIdsReturnType,
    listBaseline: ListBaselineReturnType,
    listBaselineSystems: ListBaselineSystemsReturnType,
    listBaselineSystemsIds: ListBaselineSystemsIdsReturnType,
    listPackages: ListPackagesReturnType,
    listSystemAdvisories: ListSystemAdvisoriesReturnType,
    listSystemAdvisoriesIds: ListSystemAdvisoriesIdsReturnType,
    listSystemTags: ListSystemTagsReturnType,
    listSystems: ListSystemsReturnType,
    listSystemsIds: ListSystemsIdsReturnType,
    listTemplate: ListTemplateReturnType,
    listTemplateSystems: ListTemplateSystemsReturnType,
    listTemplateSystemsIds: ListTemplateSystemsIdsReturnType,
    packageSystems: PackageSystemsReturnType,
    packageSystemsIds: PackageSystemsIdsReturnType,
    packageVersions: PackageVersionsReturnType,
    removeBaselineSystems: RemoveBaselineSystemsReturnType,
    removeTemplateSystems: RemoveTemplateSystemsReturnType,
    systemPackages: SystemPackagesReturnType,
    systemVmaasJson: SystemVmaasJsonReturnType,
    systemYumUpdates: SystemYumUpdatesReturnType,
    updateBaseline: UpdateBaselineReturnType,
    updateTemplateSystems: UpdateTemplateSystemsReturnType,
    viewAdvisoriesSystems: ViewAdvisoriesSystemsReturnType,
    viewSystemsAdvisories: ViewSystemsAdvisoriesReturnType,


};

export const PatchClient = (BASE_PATH: string, instance?: ApiConfig) => {
  return APIFactory<typeof endpointList, endpointReturnTypes>(BASE_PATH, endpointList, instance);
}

export default PatchClient;
