/* tslint:disable */
/* eslint-disable */
import type { AxiosStatic } from 'axios'
import { APIFactory } from '@redhat-cloud-services/javascript-clients-shared/dist/utils';
import { ApiConfig } from '@redhat-cloud-services/javascript-clients-shared/dist/common'
import {
    addTemplateSubscribedSystem,AddTemplateSubscribedSystemReturnType,
    deletesystem,DeletesystemReturnType,
    detailAdvisory,DetailAdvisoryReturnType,
    detailSystem,DetailSystemReturnType,
    exportAdvisories,ExportAdvisoriesReturnType,
    exportAdvisorySystems,ExportAdvisorySystemsReturnType,
    exportPackageSystems,ExportPackageSystemsReturnType,
    exportPackages,ExportPackagesReturnType,
    exportSystemAdvisories,ExportSystemAdvisoriesReturnType,
    exportSystemPackages,ExportSystemPackagesReturnType,
    exportSystems,ExportSystemsReturnType,
    exportTemplateSystems,ExportTemplateSystemsReturnType,
    latestPackage,LatestPackageReturnType,
    listAdvisories,ListAdvisoriesReturnType,
    listAdvisoriesIds,ListAdvisoriesIdsReturnType,
    listAdvisorySystems,ListAdvisorySystemsReturnType,
    listAdvisorySystemsIds,ListAdvisorySystemsIdsReturnType,
    listPackages,ListPackagesReturnType,
    listSystemAdvisories,ListSystemAdvisoriesReturnType,
    listSystemAdvisoriesIds,ListSystemAdvisoriesIdsReturnType,
    listSystemTags,ListSystemTagsReturnType,
    listSystems,ListSystemsReturnType,
    listSystemsIds,ListSystemsIdsReturnType,
    listTemplate,ListTemplateReturnType,
    listTemplateSystems,ListTemplateSystemsReturnType,
    listTemplateSystemsIds,ListTemplateSystemsIdsReturnType,
    packageSystems,PackageSystemsReturnType,
    packageSystemsIds,PackageSystemsIdsReturnType,
    packageVersions,PackageVersionsReturnType,
    removeTemplateSystems,RemoveTemplateSystemsReturnType,
    systemPackages,SystemPackagesReturnType,
    systemVmaasJson,SystemVmaasJsonReturnType,
    systemYumUpdates,SystemYumUpdatesReturnType,
    updateTemplateSystems,UpdateTemplateSystemsReturnType,
    viewAdvisoriesSystems,ViewAdvisoriesSystemsReturnType,
    viewSystemsAdvisories,ViewSystemsAdvisoriesReturnType,

  } from './index';

const endpointList = {
      addTemplateSubscribedSystem,
    deletesystem,
    detailAdvisory,
    detailSystem,
    exportAdvisories,
    exportAdvisorySystems,
    exportPackageSystems,
    exportPackages,
    exportSystemAdvisories,
    exportSystemPackages,
    exportSystems,
    exportTemplateSystems,
    latestPackage,
    listAdvisories,
    listAdvisoriesIds,
    listAdvisorySystems,
    listAdvisorySystemsIds,
    listPackages,
    listSystemAdvisories,
    listSystemAdvisoriesIds,
    listSystemTags,
    listSystems,
    listSystemsIds,
    listTemplate,
    listTemplateSystems,
    listTemplateSystemsIds,
    packageSystems,
    packageSystemsIds,
    packageVersions,
    removeTemplateSystems,
    systemPackages,
    systemVmaasJson,
    systemYumUpdates,
    updateTemplateSystems,
    viewAdvisoriesSystems,
    viewSystemsAdvisories,


};

type endpointReturnTypes = {
      addTemplateSubscribedSystem: AddTemplateSubscribedSystemReturnType,
    deletesystem: DeletesystemReturnType,
    detailAdvisory: DetailAdvisoryReturnType,
    detailSystem: DetailSystemReturnType,
    exportAdvisories: ExportAdvisoriesReturnType,
    exportAdvisorySystems: ExportAdvisorySystemsReturnType,
    exportPackageSystems: ExportPackageSystemsReturnType,
    exportPackages: ExportPackagesReturnType,
    exportSystemAdvisories: ExportSystemAdvisoriesReturnType,
    exportSystemPackages: ExportSystemPackagesReturnType,
    exportSystems: ExportSystemsReturnType,
    exportTemplateSystems: ExportTemplateSystemsReturnType,
    latestPackage: LatestPackageReturnType,
    listAdvisories: ListAdvisoriesReturnType,
    listAdvisoriesIds: ListAdvisoriesIdsReturnType,
    listAdvisorySystems: ListAdvisorySystemsReturnType,
    listAdvisorySystemsIds: ListAdvisorySystemsIdsReturnType,
    listPackages: ListPackagesReturnType,
    listSystemAdvisories: ListSystemAdvisoriesReturnType,
    listSystemAdvisoriesIds: ListSystemAdvisoriesIdsReturnType,
    listSystemTags: ListSystemTagsReturnType,
    listSystems: ListSystemsReturnType,
    listSystemsIds: ListSystemsIdsReturnType,
    listTemplate: ListTemplateReturnType,
    listTemplateSystems: ListTemplateSystemsReturnType,
    listTemplateSystemsIds: ListTemplateSystemsIdsReturnType,
    packageSystems: PackageSystemsReturnType,
    packageSystemsIds: PackageSystemsIdsReturnType,
    packageVersions: PackageVersionsReturnType,
    removeTemplateSystems: RemoveTemplateSystemsReturnType,
    systemPackages: SystemPackagesReturnType,
    systemVmaasJson: SystemVmaasJsonReturnType,
    systemYumUpdates: SystemYumUpdatesReturnType,
    updateTemplateSystems: UpdateTemplateSystemsReturnType,
    viewAdvisoriesSystems: ViewAdvisoriesSystemsReturnType,
    viewSystemsAdvisories: ViewSystemsAdvisoriesReturnType,


};

export const PatchClient = (BASE_PATH: string, instance?: ApiConfig) => {
  return APIFactory<typeof endpointList, endpointReturnTypes>(BASE_PATH, endpointList, instance);
}

export default PatchClient;
