// tslint:disable
/**
 * Patchman-engine API
 * Description here
 *
 * The version of the OpenAPI document: v1.6.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
