import { APIFactory } from '@redhat-cloud-services/javascript-clients-shared/utils';
import { ApiConfig } from '@redhat-cloud-services/javascript-clients-shared/common'
import {
    apiGroupCreateGroup,
    apiGroupDeleteGroups,
    apiGroupDeleteHostsFromDifferentGroups,
    apiGroupGetGroupList,
    apiGroupGetGroupsById,
    apiGroupPatchGroupById,
    apiHostDeleteAllHosts,
    apiHostDeleteHostById,
    apiHostDeleteHostsByFilter,
    apiHostGetHostById,
    apiHostGetHostExists,
    apiHostGetHostList,
    apiHostGetHostSystemProfileById,
    apiHostGetHostTagCount,
    apiHostGetHostTags,
    apiHostGroupAddHostListToGroup,
    apiHostGroupDeleteHostsFromGroup,
    apiHostGroupGetHostListByGroup,
    apiHostHostCheckin,
    apiHostMergeFacts,
    apiHostPatchHostById,
    apiHostReplaceFacts,
    apiHostViewsGetHostViews,
    apiResourceTypeGetResourceTypeGroupsList,
    apiResourceTypeGetResourceTypeList,
    apiStalenessCreateStaleness,
    apiStalenessDeleteStaleness,
    apiStalenessGetDefaultStaleness,
    apiStalenessGetStaleness,
    apiStalenessUpdateStaleness,
    apiSystemProfileGetOperatingSystem,
    apiSystemProfileGetSapSids,
    apiSystemProfileGetSapSystem,
    apiSystemProfileValidateSchema,
    apiTagGetTags,
    apiViewsCloneView,
    apiViewsCreateView,
    apiViewsDeleteDefaultView,
    apiViewsDeleteView,
    apiViewsGetViewById,
    apiViewsGetViewsList,
    apiViewsPatchView,
    apiViewsSetDefaultView,

  } from './index';

const endpointList = {
      apiGroupCreateGroup,
    apiGroupDeleteGroups,
    apiGroupDeleteHostsFromDifferentGroups,
    apiGroupGetGroupList,
    apiGroupGetGroupsById,
    apiGroupPatchGroupById,
    apiHostDeleteAllHosts,
    apiHostDeleteHostById,
    apiHostDeleteHostsByFilter,
    apiHostGetHostById,
    apiHostGetHostExists,
    apiHostGetHostList,
    apiHostGetHostSystemProfileById,
    apiHostGetHostTagCount,
    apiHostGetHostTags,
    apiHostGroupAddHostListToGroup,
    apiHostGroupDeleteHostsFromGroup,
    apiHostGroupGetHostListByGroup,
    apiHostHostCheckin,
    apiHostMergeFacts,
    apiHostPatchHostById,
    apiHostReplaceFacts,
    apiHostViewsGetHostViews,
    apiResourceTypeGetResourceTypeGroupsList,
    apiResourceTypeGetResourceTypeList,
    apiStalenessCreateStaleness,
    apiStalenessDeleteStaleness,
    apiStalenessGetDefaultStaleness,
    apiStalenessGetStaleness,
    apiStalenessUpdateStaleness,
    apiSystemProfileGetOperatingSystem,
    apiSystemProfileGetSapSids,
    apiSystemProfileGetSapSystem,
    apiSystemProfileValidateSchema,
    apiTagGetTags,
    apiViewsCloneView,
    apiViewsCreateView,
    apiViewsDeleteDefaultView,
    apiViewsDeleteView,
    apiViewsGetViewById,
    apiViewsGetViewsList,
    apiViewsPatchView,
    apiViewsSetDefaultView,


};

export const HostInventoryClient = (BASE_PATH: string, instance?: ApiConfig) => {
  return APIFactory(BASE_PATH, endpointList, instance);
}

export default HostInventoryClient;
