name: Automatically generate new packages

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17

      - name: Install dependencies
        run: npm ci

      - name: Generate packages
        run: npm run generate

      - name: Commit changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          git add .
          git commit -m "Regenerate packages"
          git push origin master
