# This workflow will review the current status of the APIs.
# If there are updates in the APIs, it will re-generate the clients and open a PR with the change.

name: Syncing APIs and Generating Clients

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write  # Needed for create-pull-request action
  pull-requests: write  # Needed for create-pull-request action

jobs:
  build:
    if: github.repository == 'RedHatInsights/javascript-clients'
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        token: ${{ secrets.BOT_GH_TOKEN }}
    - uses: './.github/actions/setup-environment'
    - run: npm ci
    - name: Generate clients
      run: npm run nx:reset && npm run generate
    - name: Build packages
      run: npm run build:no-cache
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7
      with:
        token: ${{ secrets.BOT_GH_TOKEN }}
        title: 'chore(nightly-sync): API sync and client generation'
        body: |
          There were some changes in the contents of the APIs. Clients were re-generated reflecting these changes.
        commit-message: 'chore(nightly-sync): API sync and client generation'
        delete-branch: true
        author: "GitHub <noreply@github.com>"
